[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_solana = "DQ8H7EGgWpxqv6rV9rj2DVWyyRZvGwj8PvRYjyfQG8Qo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./key/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
