[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_solana = "8FLVYw42CfMjcbYuvB6tKz2Ms4Pe6QXoaReqZEoY1NkQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./key/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
